//Nutz默认配置
{
	"EL":{
		"custom":[
			"org.nutz.el.opt.custom.Max",
			"org.nutz.el.opt.custom.Min",
			"org.nutz.el.opt.custom.Trim",
			"org.nutz.el.opt.custom.MakeUUID",
			"org.nutz.el.opt.custom.DoBase64",
			"org.nutz.el.opt.custom.DoURLEncoder",
			"org.nutz.el.opt.custom.TimeNow",
			"org.nutz.el.opt.custom.ByMake"
		]}
}