//Nutz默认配置
{
	"EL":{
		"custom":[
			"org.nutz.el.opt.custom.Max",
			"org.nutz.el.opt.custom.Min",
			"org.nutz.el.opt.custom.Trim"
		]}
	"MVC":{
		"localization":{
			"type": "org.nutz.mvc.impl.NutMessageLoader",
			"value":""
		},
		"iocBy":{
			"type":"",
			"args":[]
		},
		"setupBy":{
			"value":"org.nutz.mvc.Setup",
			"args":[]
		}
	}
}