DROP TABLE DAO_BASE;
DROP TABLE DAO_COUNTRY;
DROP TABLE DAO_PLATOON;
DROP TABLE DAO_FIGHTER;
DROP TABLE DAO_M_BASE_FIGHTER;
DROP TABLE DAO_WAVEBAND;

DROP TABLE DAO_SUPPORTED_TYPE;
DROP TABLE DAO_TOOL_ABC;
DROP TABLE T_STABBER;
DROP TABLE T_PET;

DROP TABLE T_DOG;
DROP TABLE T_RESIDENT;
DROP TABLE T_WORKER;
DROP TABLE T_KILLER;
DROP TABLE T_KILLER_RE;

DROP TABLE TRANS_COMPANY;
DROP TABLE TRANS_MASTER;
DROP TABLE TRANS_CAT;


DROP SEQUENCE DAO_COUNTRY_ID_SEQ;
DROP SEQUENCE DAO_PLATOON_ID_SEQ;
DROP SEQUENCE DAO_FIGHTER_ID_SEQ;

DROP SEQUENCE DAO_SUPPORTED_TYPE_ID_SEQ;
DROP SEQUENCE T_STABBER_ID_SEQ;
DROP SEQUENCE T_PET_ID_SEQ;

DROP SEQUENCE TRANS_COMPANY_ID_SEQ;
DROP SEQUENCE TRANS_MASTER_ID_SEQ;
DROP SEQUENCE TRANS_CAT_ID_SEQ;

DROP SEQUENCE T_RESIDENT_ID_SEQ;
DROP SEQUENCE T_WORKER_WID_SEQ;
DROP SEQUENCE T_KILLER_ID_SEQ;